blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/codinux-gmbh/kCSV/discussions
    about: For questions and general discussions please use Discussions and do not open an issue.
